rss_feeds:
  - name: "The Hacker News"
    url: "https://feeds.feedburner.com/TheHackersNews"
  - name: "BleepingComputer"
    url: "https://www.bleepingcomputer.com/feed/"
  - name: "ThreatPost"
    url: "https://threatpost.com/feed/"
  - name: "CISA"
    url: "https://www.cisa.gov/news.xml"

reddit_feeds:
  - name: "cybersecurity"
  - name: "netsec"
  - name: "hacking"
  - name: "AskNetsec"
  - name: "InformationSecurity"

keywords:
  - authentication
  - botnet
  - data breach
  - DDoS
  - encryption
  - exploit
  - firewall
  - malware
  - Man in the middle attack
  - phising
  - ransomware
  - spoofing
  - spyware
  - trojan horse
  - virus
  - vpn
  - worm
  - rootkit
  - BYOD (bring your own device)
  - Pen-testing
  - social engineering
  - deepfake
  - Advanced persistent threat (APT)
  - brute force attack
  - crypto-jacking
  - cyberbullying
  - dark web
  - endpoint detection and response (EDR)
  - fileless malware
  - Identity and Access management (IAM)
  - Insider Threat
  - Intrusion prevention system (IPS)
  - keylogger
  - patch
  - malvertising
  - sandboxing
  - security operations center (SOC)
  - threat hunting
  - WAF
  - zero-day exploit
  - honeypot
  - shadow IT
  - cookie
  - metadata
  - deep weeb
  - digital signature
  - CVE
  - CVSS
